### ISSUE TITLE
Applicative-lifted versions of || and &&

### ISSUE THREAD

**Issue by radix** [snoyberg/classy-prelude#109]
There are [many implementations of lifted || and && throughout stackage](https://www.stackage.org/lts-4.1/hoogle?q=Applicative+f+%3D%3E+f+Bool+-%3E+f+Bool+-%3E+f+Bool) -- it seems it would be nice for ClassyPrelude to expose

```
(<||>) = liftA2 (||)
(<&&>) = liftA2 (&&)
```

or different spellings.

These are particularly useful for combining predicate functions (using the applicative instance for functions), for example `(=="foo") <||> (=="bar")`, in addition to being useful with any applicatives-of-bool, such as `ioGetFoo <&&> ioGetBar`.

I'm happy to submit a PR if this idea is acceptable.

**Comment by gregwebs** [comment]
seems like a good idea to me

**Comment by snoyberg** [comment]
Agreed, I'd be in favor of such a PR.

**Comment by snoyberg** [comment]
Fixed by #125, thanks @talw!

**Comment by minad** [comment]
I also commented at the corresponding protolude issue - You might want to note that the operators are not short-circuiting. In [extra](https://hackage.haskell.org/package/extra-1.5.1/docs/Control-Monad-Extra.htmll) the short-circuiting variants are defined in terms of `ifM` for `Monad`.

~~~ haskell
(||^) :: Monad m => m Bool -> m Bool -> m Bool
(||^) a b = ifM a (return True) b

(&&^) :: Monad m => m Bool -> m Bool -> m Bool
(&&^) a b = ifM a b (return False)

**Comment by talw** [comment]
This is a great point!
Since `||` and `&&` ARE short-circuiting functions, I think it's best that these 2 operators will short-circuit as well.

However, I'm very busy as of late, and won't be able to PR this trivial commit in the upcoming weeks.
Once I'm back to my normal routine I'll PR this, unless someone beats me to it :).

**Comment by minad** [comment]
@talw May I point you to the discussion at [protolude](https://github.com/sdiehl/protolude/issues/40)? Do you suggest replacing the non-short-circuiting versions?
