### ISSUE TITLE
How well would classy-prelude play with numeric-prelude?

### ISSUE THREAD

**Issue by kozross** [snoyberg/classy-prelude#110]
I like the ideas behind both of these alternative Preludes, and would like to be able to use them together. However, I'm not sure if there'd be clashes between them, and wanted to ask if there are any potential tripping hazards involved. For reference, numeric-prelude is [here][1].

[1]:  http://hackage.haskell.org/package/numeric-prelude

**Comment by gregwebs** [comment]
Give it a try a

**Comment by gregwebs** [comment]
Give it a try and let us know

**Comment by kozross** [comment]
The answer is 'not particularly well', it would appear - ```numeric-prelude``` has a lot of tweaks related to the numeric hierarchy (unsurprisingly), making its use together with ```classy-prelude``` a qualified import bonanza.

Hence, I will close the issue.

**Comment by gregwebs** [comment]
Interesting. Classy-prelude doesn't do much with numbers. Where are the clashes?
