### ISSUE TITLE
confusing intersect of Lists of Tuples

### ISSUE THREAD

**Issue by trin-cz** [snoyberg/classy-prelude#120]
I'm having a lot of fun now, with Atom IDE, Yesod, Riak and Reactive Banana. Thanks everyone, who made this possible. However ...

> [(1,0)] `intersect` [(1,1)]
[(1,0)]

This incompatibility with Data.List.intersect confused me a lot. Is it a feature?

**Comment by snoyberg** [comment]
The reason for this distinction is that lists of pairs are treated by the
mono-traversable library as an association list, and act like `Map`s. The
intersection is occurring only on the first value in each tuple.

**Comment by trin-cz** [comment]
I was afraid of this. Ok, it makes sense. Thank you. Let's close this.
